### ISSUE TITLE
Nontrivial tests with many off-eq particles

### ISSUE THREAD

**Issue by niemilau** [Wall-Go/WallGo#144]
1. Treat left and right handed tops separately with QCD matrix elements only, compare with the case of "just one top"

2. Same as 1 but add chiral SU(2) interactions. Limit g -> 0 should reproduce case 1 

3. Suppose we have N identical top quarks, all out of equilibrium. We can generate matrix elements and collisions in two ways:
(i) List each of these as a separate off-eq particle and compute NxN deltaF matrix. Then solve EOM with those
(ii) Add the particles together already in matrix element, effectively reducing the case to 1 off-eq particle (Andreas)

**Comment by pschicho** [comment]
The following cases have been studied:

1. using a 2x2 topL/topR-quark matrix. The differences to `just-one-top` were found to be of the size of taking different seeds in the integration.

2. gives same matrix elements as 1.

3. it is technically possible to do (ii) but in practice we always do (i). Integration results should depend on the overall dofs.
