### ISSUE TITLE
Verbosity parameter to silence outputs

### ISSUE THREAD

**Issue by tvitenka** [Wall-Go/WallGo#156]
I suggest there to be way to silence many parts of the code, for example 'sor/Wallgo/EOM.py' shout outs " print(f"\nTrying {wallVelocity=}")" multiple times for single parameter point run, and would be nice to suppress these printouts if user so wishes. I am not implementing this yet before consultation how this verbosity option should be implemented most elegantly. I would set a flag in config for this, but other solutions migth be more elegant?

**Comment by og113** [comment]
Resolved in PR #305
