### ISSUE TITLE
Dependence on T0 scale

### ISSUE THREAD

**Issue by og113** [Wall-Go/WallGo#196]
In principle physical results shouldn't depend on the scale T0 used in the mapping between momentum coordinates and their compactified versions. However, taking a look explicitly it seems that there is a quite noticeable dependence; see https://github.com/Wall-Go/WallGo/pull/190#issuecomment-2120749053. This needs investigating further.

**Comment by jorindevandevis** [comment]
We have a section in the draft investigating this issue. Indeed, for a poor choice of T0 (called meanFreePathScale in the code), the results depend on it. This can be somewhat compensated by choosing a larger M.
