### ISSUE TITLE
Configure examples explicitly so that they don't depend on whatever our defaults are

### ISSUE THREAD

**Issue by niemilau** [Wall-Go/WallGo#262]
Vicious cycle: Someone changes WallGo defaults in a PR -> example models start giving different results, bug is suspected -> time wasted -> defaults changed again to reproduce earlier example numbers.

If we use the examples as sort of "health checks" then they must be configured to not depend on defaults, just like unit tests.

Related: #261 #248

**Comment by jorindevandevis** [comment]
implemented in https://github.com/Wall-Go/WallGo/pull/311
