### ISSUE TITLE
Improve config variables

### ISSUE THREAD

**Issue by niemilau** [Wall-Go/WallGo#293]
# The problem

WallGo internal routines depend on bunch of variables that are not directly part of the "public" WallGoManager API, but are still important enough that we want to allow users to configure them depending on their needs. This includes variables like spatial/momentum grid sizes, error tolerances for various solvers and lower/upper bounds on things like the wall offset. Many of these must either be passed in to the internal "worker" classes like EOM or BoltzmannSolver at the time of their construction, or to internal functions of these classes.

The challenge is to find a convenient way of exposing these variables to the user. Currently this is handled by the Config class, which is just a thin wrapper around ConfigParser (from Python standard lib), and the WallGoManager is responsible for reading variables from a global Config and passing them to right functions in the WallGo pipeline. The Config is filled at WallGo init time by reading a packaged .ini file.

This approach has several problems:
1. Has global state, even though it'd be enough to have each WallGoManager instance manage its own Config.
2. Since Config currently is basically just a ConfigParser, all config variables are stored as strings in a dict. No type hinting or IDE help whatsoever.
3. Modifying the configs at runtime is possible by accessing the Config instance directly, but cumbersome due to the above.
4. It is also not very clear where each variable is actually used in the pipeline without looking at WallGoManager code.

# Solution draft

A big improvement would be to move away from string-based config variable access. This immediately solves points 2 and 4. Could be done by replacing the current Config class by a dataclass that has clear member attributes for the config variables, with proper docstrings explaining how WallGo uses them.

Point 1 is solved by removing global Config state and instead creating a Config instance during WallGoManager initialization. Access and modify eg. by manager.config.someVariable = ..., solving point 3.

If we go with this, the following should be taken into consideration:
- A valid default Config can be constructed without relying on external or model-dependent input. For this, I feel it's best to make all our config variables dimensionless so that they are eg. in units of the nucleation temperature. As far as the current .ini files goes, seems to already be the case.

 - For consistency and clarity, I think it'd be best to handle all Config logic inside the WallGoManager and avoid accessing Config instances directly in other parts of the WallGo pipeline. Eg. BoltzmannSolver has no access to Config, it can only receive relevant config variables as inputs from either the manager (intended use) or directly from the user (advanced use). May already be the case, but should be checked. Ensuring we have no global Config state should help with this.

- Do we want one monolithic Config class that contains all variables, or is it organized into many smaller dataclasses? The latter option at least sounds more easily manageable.
 
# Considerations regarding .ini files

Do we keep built-in support for .ini files?

- If yes, a simple way of implementing this would be to give the Config class a function that creates a temporary ConfigParser object, reads an input .ini, and converts contents of the resulting ConfigParser to internal Config attributes.
- Follow-up to the above, even if we allow .ini parsing I think the Config class should have valid defaults even without reading any .ini. The behavior should be more like: (i) Construct Config object so that it has reasonably good defaults (ii) Read .ini and replace **only** the variables that the .ini overrides. Other variables are left untouched.
- This is so that we don't force .inis on users, but still provide a fairly standard way of passing data without modifying .py files directly.
- Whether WallGoManager reads some default, packaged .ini during its construction is a design question. I vote no, just for simplicity.

**Comment by benoitlaurent96** [comment]
Thanks Lauri, that's very clear! 
I think it would be a good idea to keep the possibility of having a .ini file without making it a requirement. A function 'readConfigFile' sounds like a good solution to me. 
I also think it would be better to organize it into several smaller dataclasses. But should we store them all in a master 'Config' class? So calling one parameter would look like manager.config.eomConfig.parameter. The obvious advantage is that the readConfigFile function would be in Config, and it would update all the dataclasses at once instead of having to call it manually in each of them.

**Comment by niemilau** [comment]
Yeah, it still makes sense to group them in a bigger class.
